version: '3.7'

services:
  db:
    image: postgres:13
    container_name: backend
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=coopers
    volumes:
      - backend:/data/postgres

volumes:
  backend:
    driver: local